== Simple Example

* Next we will play with managed resources
* To create external resources

== Managed Resources

Managed resources are the kubernetes representation of the external objects we want to create.

== Learning Goals:

* `forProvider` and `atProvider`
* `deletionPolicy`

Start two watches and keep them running: 

For following the resources created by crossplane

----
watch -n 1 kubectl get pods -n default` 
----

For following the crossplane resources

----
watch -n 1 kubectl get crossplane
----

== Create a Managed Resource:

[source,shell]
----
kubectl apply -f provider-kubernetes/01-ManagedResources/simple.pod.yaml
kubectl get deploy,pods -n default
----

Expected: The external resource (`Pod`) is being created

[source,shell]
----
kubectl describe object.kubernetes.crossplane.io kubernetes-provider-pod
kubectl get object kubernetes-provider-yaml
----

Expected: We can see the manifest of our external resource in `atProvider`.

== Reconciliation

Add a label to the managed resource

[source,shell]
----
kubectl patch --type=merge object.kubernetes.crossplane.io kubernetes-provider-pod -p '{"spec":{"forProvider":{"manifest":{"metadata":{"labels":{"changes":"propagate"}}}}}}'
kubect describe pod -n default pod
----

Expected: `forProvider` is to `atProvider` what `spec` is to `status`. The change propagated, the provider reconciled the external resource.

remove the labels from the external resource

[source,shell]
----
kubectl label pods -n default pod changes- example-
kubect describe pod -n default pod
----

Expected: The labels are added again by the provider-kubernetes. Reconciliation works in both directions.

== Reconciliation

Delete the external resource

[source,shell]

----
kubectl delete pod -n default pod
kubectl get pods -n default
----

Expected: The external resource vanishes and gets recreated.

So Crossplane acts like a ReplicaSet/ArgoCD/Flux

== Delete the managed resource:

[source,shell]
----
kubectl delete object.kubernetes.crossplane.io kubernetes-provider-pod
kubectl get pods -n default
----

Expected: The external resource vanishes as well

== Create another managed resource

[source,shell]
----
kubectl apply -f provider-kubernetes/01-ManagedResources/simple.deploy.yaml
kubectl get deployments -n default
----

Expected: An external resource (`Deployment`) was created.

== Delete the managed resource

[source,shell]
----
kubectl delete object.kubernetes.crossplane.io kubernetes-provider-deploy
kubectl get deployments -n default
----
Expected: The external resource stays behind

The difference lies in the `deletionPolicy`. The managed resource for the `Deployment` had a `deletionPolicy` of `Orphan`, so the provider will not try to delete the external resource.
