== Simple Example

* Next we will play with managed resources
* To create external resources

== Managed Resources

Managed resources are the kubernetes representation of the external objects we want to create.

== Learning Goals:

* `forProvider` and `atProvider`
* Providers are not "transparent"
* `deletionPolicy`

== Prepare the Terminal
Switch to the topics directory

[source,shell]
----
cd provider-kubernetes/ManagedResources
----

For following the resources created by crossplane

[source,shell]
----
watch -n 1 kubectl get pods,deployments -n default 
----

For following the crossplane resources

[source,shell]
----
watch -n 1 kubectl get crossplane
----

== Create a Managed Resource:

[source,shell]
----
kubectl apply -f simple.pod.yaml
kubectl get deploy,pods -n default
----

Expected: The external resource (`Pod`) is being created

[source,shell]
----
kubectl describe object.kubernetes.crossplane.io kubernetes-provider-pod
kubectl get object kubernetes-provider-pod -o yaml
----

Expected: We can see the manifest of our external resource in `atProvider`.

== Reconciliation

Delete the external resource

[source,shell]
----
kubectl delete pod -n default kubernetes-provider-pod
kubectl get pods -n default
----

Expected: The Pod is recreated (it takes a while)

== Reconciliation

Delete the managed resource

[source,shell]
----
kubectl delete object kubernetes-provider-pod
kubectl get objects,pods
----

Expected: Both Pod and Managed Resource are gone

== Reconciliation

Let's create another resource and see how changes propagate

[source,shell]
----
kubectl apply -f simple.deploy.yaml
kubectl get pods,deployments
kubectl patch --type=merge object kubernetes-provider-deploy -p '{"spec":{"forProvider":{"manifest":{"spec":{"replicas": 2}}}}}'
kubect get pods,deployments
----

Expected: We have now have two replicas :)

== Reconciliation

Let's do it the other way around and see what happens

[source,shell]
----
kubectl scale --replicas=3 -n default deployment kubernetes-provider-deploy
----

* We expected that first have 3 Replicas, then it reconciles back to 2
* This is a https://github.com/crossplane-contrib/provider-kubernetes/issues/37["known issue"]
** provider-kubernetes uses the `last-applied-configuration` to detect drift 🤯

== Reconciliation
So, lets's do it as the issue author Koloss suggests:

[source, shell]
----
kubectl get deployment kubernetes-provider-deploy -oyaml -n default | sed 's/^  replicas: 3/  replicas: 3/' | kubectl apply -f -
----

* Now it scales back to 2, as specified in the Managed Resource
* I have to know about implementation details of my Provider ☝️

== Cleanup? 🧹

Let's delete the ManagedResource

[source,shell]
----
kubectl delete object kubernetes-provider-deploy
kubectl get deployments -n default
----

* Deployment and Pods are gone?
* It is still around! 🤔
* Deletion Policy!
** `Orphan` - Abandon the external resource
** `Delete` - Clean up after yourself

== Cleanup! 🧹
Let's clean up the rest:

[source,shell]
----
kubectl delete deployment -n default kubernetes-provider-deploy
kubectl get deployments -n default
----

* Now it is nice and clean ✨
